server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    hosts:
      - metrics.valuxa.shop
    path: /
    
  extraArgs:
    web.enable-remote-write-receiver: ""
