apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/KristijanBoshev/server-configs.git
      targetRevision: main
      ref: values
      path: ""
    - repoURL: oci://ghcr.io/m0nsterrr/helm-charts
      chart: homepage
      targetRevision: 4.1.4
      helm:
        valueFiles:
          - $values/apps/homepage/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
