initChownData:
  enabled: false

persistence:
  type: pvc
  enabled: true

securityContext:
  fsGroup: 472
  runAsUser: 472

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"

  hosts:
    - grafana.valuxa.shop

grafana.ini:
  server:
    root_url: https://grafana.valuxa.shop

  auth.generic_oauth:
    enabled: true
    client_id: ${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
    client_secret: ${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
    scopes: openid profile email groups
    auth_url: https://auth.valuxa.shop/application/o/authorize/
    token_url: https://auth.valuxa.shop/application/o/token/
    api_url: https://auth.valuxa.shop/application/o/userinfo/
    use_refresh_token: true
    role_attribute_path: contains(groups[*], 'grafana-admins') && 'Admin' || contains(groups[*], 'grafana-editors') && 'Editor' || 'Viewer'

envFromSecret: grafana-oidc-secret

