apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "K8YkQIriXFpbshINrPE7pmMhpxSqawueMgA5jJSP"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "gT9Jz7VhcIsW5OhbVVNoKWh9JexORPFIrOwLDhWn9UYXuWq4vbpOueDaL25RTSJlUAS5JRipgdfaMR5Cm6V0sDaKyW1RMBkIOOgupAvjMHc1YNkfEps66HU3Zt7HlcCe"
