global:
  domain: argo.valuxa.shop

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: "argo.valuxa.shop"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    tls: true

configs:
  params:
    server.insecure: true
